export const USER_ACTION_TYPES = {
	SET_CURRENT_USER   : 'SET_CURRENT_USER',
	SET_AUTHTOKEN_USER : 'SET_AUTHTOKEN_USER',
	SET_ROLES_USER     : 'SET_ROLES_USER',
	SET_CUSTOMERS      : 'SET_CUSTOMERS',
	SET_ACCTS_USER     : 'Set_ACCTS_USER',
	SET_CUST_USER	   : 'SET_CUST_USER'
};
