export const PRICING_ACTION_TYPES = {
    ADD_PRICING_MOD: 'ADD_PRICING_MOD',
    DELETE_PRICING_MOD: 'DELETE_PRICING_MOD',
    UPDATE_PRICING_MOD: 'UPDATE_PRICING_MOD',
    RESET_PRICING_MOD: 'RESET_PRICING_MOD',
    SET_CUSTOMER_PRICING_MOD: 'SET_CUSTOMER_PRICING_MOD',
    SHOW_ALERT_PRICING_MOD: 'SHOW_ALERT_PRICING_MOD'
};